// Multi-format 3D export: OBJ + GLB (binary glTF)
import { computeNormal, type Triangle } from "./stl-utils";

// ────────────────────────────────────────────────────────────
// OBJ Exporter
// ────────────────────────────────────────────────────────────

/**
 * Export triangles to Wavefront OBJ format.
 * Produces indexed geometry (shared vertices where possible).
 */
export function exportToObj(triangles: Triangle[], modelName = "model"): string {
  const lines: string[] = [];
  lines.push(`# Generated by Image to STL Converter`);
  lines.push(`# https://www.image-2-stl.com`);
  lines.push(`o ${modelName}`);
  lines.push("");

  // Collect unique vertices and normals
  const vertexMap = new Map<string, number>();
  const vertices: [number, number, number][] = [];
  const normals: [number, number, number][] = [];
  const faces: number[][] = [];

  function getVertexIndex(v: [number, number, number]): number {
    const key = `${v[0].toFixed(6)},${v[1].toFixed(6)},${v[2].toFixed(6)}`;
    const existing = vertexMap.get(key);
    if (existing !== undefined) return existing;
    const idx = vertices.length;
    vertices.push(v);
    vertexMap.set(key, idx);
    return idx;
  }

  for (const tri of triangles) {
    const faceIndices: number[] = [];
    for (const v of tri.vertices) {
      faceIndices.push(getVertexIndex(v) + 1); // OBJ is 1-indexed
    }
    normals.push(tri.normal);
    faces.push(faceIndices);
  }

  // Write vertices
  for (const v of vertices) {
    lines.push(`v ${v[0].toFixed(6)} ${v[1].toFixed(6)} ${v[2].toFixed(6)}`);
  }

  lines.push(`# ${vertices.length} vertices`);
  lines.push("");

  // Write normals
  for (const n of normals) {
    lines.push(`vn ${n[0].toFixed(6)} ${n[1].toFixed(6)} ${n[2].toFixed(6)}`);
  }

  lines.push(`# ${normals.length} normals`);
  lines.push("");

  // Write faces (with normal indices)
  for (let i = 0; i < faces.length; i++) {
    const f = faces[i];
    const ni = i + 1; // normal index (1 per face in our case)
    lines.push(`f ${f[0]}//${ni} ${f[1]}//${ni} ${f[2]}//${ni}`);
  }

  return lines.join("\n");
}

// ────────────────────────────────────────────────────────────
// GLB (Binary glTF) Exporter
// ────────────────────────────────────────────────────────────

function buildGlbJson(
  positions: Float32Array,
  normals: Float32Array,
  indices: Uint32Array,
  posMin: [number, number, number],
  posMax: [number, number, number],
): object {
  const posBytes = positions.byteLength;
  const nrmBytes = normals.byteLength;
  const idxBytes = indices.byteLength;

  // Pad indices to 4-byte alignment
  const idxPadded = Math.ceil(idxBytes / 4) * 4;
  const totalBytes = posBytes + nrmBytes + idxPadded;

  const posOff = 0;
  const nrmOff = posBytes;
  const idxOff = posBytes + nrmBytes;

  return {
    asset: { version: "2.0", generator: "Image to STL Converter" },
    scene: 0,
    scenes: [{ nodes: [0] }],
    nodes: [{ mesh: 0 }],
    meshes: [
      {
        primitives: [
          {
            attributes: { POSITION: 1, NORMAL: 2 },
            indices: 0,
            mode: 4,
          },
        ],
      },
    ],
    accessors: [
      {
        bufferView: 0,
        componentType: 5125, // UNSIGNED_INT
        count: indices.length,
        type: "SCALAR",
        max: [Math.max(...Array.from(indices.slice(0, 100)))],
        min: [0],
      },
      {
        bufferView: 1,
        componentType: 5126, // FLOAT
        count: positions.length / 3,
        type: "VEC3",
        max: posMax,
        min: posMin,
      },
      {
        bufferView: 2,
        componentType: 5126,
        count: normals.length / 3,
        type: "VEC3",
      },
    ],
    bufferViews: [
      { buffer: 0, byteOffset: idxOff, byteLength: idxBytes, target: 34963 },
      { buffer: 0, byteOffset: posOff, byteLength: posBytes, byteStride: 12, target: 34962 },
      { buffer: 0, byteOffset: nrmOff, byteLength: nrmBytes, byteStride: 12, target: 34962 },
    ],
    buffers: [{ byteLength: totalBytes }],
  };
}

/**
 * Export triangles to GLB (binary glTF 2.0) format.
 * Produces indexed geometry with per-vertex normals.
 */
export function exportToGlb(triangles: Triangle[], _modelName?: string): Blob {
  // Deduplicate vertices
  const vertexMap = new Map<string, number>();
  const posList: number[] = [];
  const nrmList: number[] = [];
  const idxList: number[] = [];

  const posMin: [number, number, number] = [Infinity, Infinity, Infinity];
  const posMax: [number, number, number] = [-Infinity, -Infinity, -Infinity];

  for (const tri of triangles) {
    const faceIdx: number[] = [];
    for (const v of tri.vertices) {
      const key = `${v[0].toFixed(6)},${v[1].toFixed(6)},${v[2].toFixed(6)}`;
      let idx = vertexMap.get(key);
      if (idx === undefined) {
        idx = posList.length / 3;
        posList.push(v[0], v[1], v[2]);
        nrmList.push(tri.normal[0], tri.normal[1], tri.normal[2]);
        vertexMap.set(key, idx);
        for (let i = 0; i < 3; i++) {
          if (v[i] < posMin[i]) posMin[i] = v[i];
          if (v[i] > posMax[i]) posMax[i] = v[i];
        }
      }
      faceIdx.push(idx);
    }
    idxList.push(faceIdx[0], faceIdx[1], faceIdx[2]);
  }

  const positions = new Float32Array(posList);
  const normals = new Float32Array(nrmList);
  const indices = new Uint32Array(idxList);

  // Fix max accessor for indices
  let maxIdx = 0;
  for (let i = 0; i < indices.length; i++) {
    if (indices[i] > maxIdx) maxIdx = indices[i];
  }

  const json = buildGlbJson(positions, normals, indices, posMin, posMax);
  // Patch max index
  (json as any).accessors[0].max = [maxIdx];

  const jsonStr = JSON.stringify(json);
  const jsonBuf = new TextEncoder().encode(jsonStr);
  // Pad JSON to 4-byte alignment with spaces
  const jsonPadded = Math.ceil(jsonBuf.byteLength / 4) * 4;

  const posBytes = positions.byteLength;
  const nrmBytes = normals.byteLength;
  const idxBytes = indices.byteLength;
  const idxPadded = Math.ceil(idxBytes / 4) * 4;
  const binTotal = posBytes + nrmBytes + idxPadded;
  const binPadded = Math.ceil(binTotal / 4) * 4;

  const totalSize = 12 + 8 + jsonPadded + 8 + binPadded;
  const buffer = new ArrayBuffer(totalSize);
  const view = new DataView(buffer);
  const u8 = new Uint8Array(buffer);

  // GLB header
  view.setUint32(0, 0x46546c67, true); // "glTF"
  view.setUint32(4, 2, true); // version
  view.setUint32(8, totalSize, true);

  // JSON chunk
  view.setUint32(12, jsonPadded, true);
  view.setUint32(16, 0x4e4f534a, true); // "JSON"
  u8.set(jsonBuf, 20);
  // Pad JSON with spaces (0x20)
  for (let i = jsonBuf.byteLength; i < jsonPadded; i++) {
    u8[20 + i] = 0x20;
  }

  // BIN chunk
  const binOffset = 20 + jsonPadded;
  view.setUint32(binOffset, binPadded, true);
  view.setUint32(binOffset + 4, 0x004e4942, true); // "BIN\0"
  const binDataOffset = binOffset + 8;

  // Write positions
  u8.set(new Uint8Array(positions.buffer), binDataOffset);
  // Write normals
  u8.set(new Uint8Array(normals.buffer), binDataOffset + posBytes);
  // Write indices
  u8.set(new Uint8Array(indices.buffer), binDataOffset + posBytes + nrmBytes);
  // binPadded padding is already zeroed from ArrayBuffer

  return new Blob([buffer], { type: "model/gltf-binary" });
}
